name: Tweet Schedule

on:
  schedule:
    - cron: '17 23 * * *' # The workflow runs every day at 08:08 am UTC time.

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' # Specify the Python version without the patch number (3.11 instead of 3.11.5)

      - name: Cache pip and downloaded packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.local/lib/python3.11/site-packages # Adjust the Python version here
          key: ${{ runner.os }}-pip-${{ hashFiles('main.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests requests_oauthlib beautifulsoup4

      - name: Run Python Script
        run: python main.py
        env:
          CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
